# Generated by Django 3.2.5 on 2021-07-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='docupload',
            field=models.FileField(default='null', upload_to=''),
        ),
    ]
