# Generated by Django 3.2.5 on 2021-07-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_docupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(default='Enter Text Here', max_length=20000)),
                ('docupload', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='docupload',
        ),
    ]
