# Generated by Django 3.2.5 on 2021-07-22 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210721_2032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uploadprofile',
        ),
    ]
